---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"
    - name: check if connection still works
      ansible.builtin.ping:

    - name: "Test CentOS-Stream-AppStream.repo is generated"
      ansible.builtin.lineinfile:
        name: '/etc/yum.repos.d/CentOS-Stream-AppStream.repo'
        line: "# CentOS-Stream-AppStream.repo"
        state: present
      check_mode: true
      register: centos_stream_repo
      failed_when: (centos_stream_repo is changed) or (centos_stream_repo is failed)

    - name: "Test CentOS-8-AppStream.repo is absent"
      ansible.builtin.file:
        path: '/etc/yum.repos.d/CentOS-Linux-AppStream.repo'
        state: absent
      check_mode: true
      register: centos_repo
      failed_when: (centos_repo is changed) or (centos_repo is failed)
